inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.2

RSpec/NestedGroups:
  Enabled: false

# TODO: Remove when drop support ruby 2.2
Layout/IndentHeredoc:
  Enabled: false
