language: ruby
rvm:
- 2.2.2
- 2.3.3
- 2.4.1
- 2.5.0
- ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install:
- gem update --system --no-document
- gem install bundler -v 1.16.1 --no-document
before_script:
- export CODECLIMATE_REPO_TOKEN=8e9db6ee5f3818e87287a6393086c2ccb9b1b83106c5bfb972211abefd2fe162
- export CI=true
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter
- bundle exec ruby examples/all.rb
- bundle exec rubocop
- bundle exec rubydoctest README.md
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: M8VEihBaynGJdlXu7TvhgqIDfpHvSP5H0RCLsvtaQ5rNoz6yrOTRcLBCWazrJopD1CvKbcFTVVLlS86fxyW9+pYhYc81mXlhtyPLNx7yXQ+Uhfrxp7/e2QLEMZEgbk2Z7XglN4rJ+t4QhWjsPL0ohJk+t1DSdFtEPK3o3RyoRrE=
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
